"""empty message

Revision ID: 50947777ff9e
Revises: 
Create Date: 2022-12-29 22:09:36.808472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50947777ff9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
